joint_state_controller: #publish all joint states
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
left_arm_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
  constraints:
    goal_time: 0.1
    stopped_velocity_tolerance: 0
    left_shoulder_pan_joint: {trajectory: 0, goal: 0.01}
    left_shoulder_lift_joint: {trajectory: 0, goal: 0.01}
    left_elbow_joint: {trajectory: 0, goal: 0.01}
    left_wrist_1_joint: {trajectory: 0, goal: 0.01}
    left_wrist_2_joint: {trajectory: 0, goal: 0.01}
    left_wrist_3_joint: {trajectory: 0, goal: 0.01}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

right_arm_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    right_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    right_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    right_elbow_joint: {trajectory: 0.1, goal: 0.1}
    right_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    right_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    right_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

left_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - left_hande_left_finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

right_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - right_hande_left_finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0


joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
    - left_hande_left_finger_joint
    - right_hande_left_finger_joint
